format_version: !!int 1

#< general information about the project >#
project:
    type: !!str "package"
    github: !!str "https://github.com/Isle-0-Skye/photon"

    name: !!str "photon"
    display_name: !!str "Photon"

    description: !!str "Library and wrapper middleman for small apps"
    #< the text to print for project --help >#
    help_text: !!str |-
        {d}command format for providing {h}photon{d} arguments is:
        {h}python /path/to/photon start_mode project_name --optional_argument=value{d}

        {d}command format for providing {h}project{d} arguments is:
        {h}python /path/to/photon start_mode project_name -- --optional_argument=value{d}

        most option start with {h}--{d} , some start with {h}-{d}
        {h}--{d} on its own is a seperator, anything after it is passed to the project
        {h}|{d} means or

        start_mode options: 
        {h}help     {r} | {h}-h{r} : {d}display this help information{r}
        {h}version  {r} | {h}-v{r} : {d}display version information for Photon {r}
        {h}run      {r} | {h}-r{r} : {d}run the selected project{r}
        {h}install  {r} | {h}-i{r} : {d}install the selected project{r}
        {h}uninstall{r}   {h}  {r} : {d}uninstall the selected project{r}
        {h}update   {r} | {h}-u{r} : {d}update the selected project{r}
        {h}list     {r} | {h}-l{r} : {d}display a list of information about a project{r}
        {h}refresh  {r}   {h}  {r} : {d}refresh data about a project

        optional_argument options:
        {h}--log-level{r} : {d}sets the log level photon will use when printing to the terminal
            value choices are: [{h}debug trace info warning error critical{d}]
            default value is {h}info{r}

    #< project version information >#
    version:
        full: !!str "1.0.0"
        released: !!str "2025-07-12"
        name: !!str "Numero Uno"

        major: !!int 1
        minor: !!int 0
        revision: !!int 0

    #< languages or translations the project supports >#
    languages: ["English"]

#< information for the installation/uninstallation/update process >#
setup:
    requires: 
        dependencies: {"system": "python3", "python_pip": "PyYAML", "python_pip": "prettytable"}
        recommends: {}
        suggests: {}

#< information about the primary language the project is made in >#
language:
    name: !!str "python"

    #< language version information >#
    version:
        full: !!str "3.12.3"

        major: !!int 3
        minor: !!int 12
        revision: !!int 3

        known_supported: [
            "3.12.3", 
            "3.12.2", 
            "3.12.1", 
            "3.12.0"
        ]

#< information about each of the major platforms, the name matches platform.system() >#
platform:
    #< ------------ >#
    Windows:
        icon: !!str 
        category: !!str 
        keywords: []
        runtime_args: []

        #< platform version information >#
        known_supported: !!bool true
        version:
            known_supported: [
                "11",
                "10"
            ]
            known_unsupported: []

    #< ------------ >#
    Linux:
        icon: !!str 
        category: !!str 
        keywords: []
        runtime_args: []

        #< platform version information >#
        known_supported: !!bool true
        version:
            known_supported: [
                "6.11.0-29-generic",
                "6.11.0-28-generic",
                "6.11.0-26-generic"
            ]
            known_unsupported: []

    #< ------------ >#
    Darwin:
        icon: !!str 
        category: !!str 
        keywords: []
        runtime_args: []

        #< platform version information >#
        known_supported: !!bool false
        version:
            known_supported: []
            known_unsupported: []
