target-version = "py312"

indent-width = 4
line-length = 100
respect-gitignore = true


[format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
indent-style = "space"
line-ending = "lf"
quote-style = "double"

[lint]
extend-select = ["TC002", "TID252"]

[lint.isort]
lines-after-imports = 2
lines-between-types = 1
force-wrap-aliases = true
combine-as-imports = true
